// @ts-nocheck
export type Lang = "fr" | "en" | "es" | "de" | "ghomala" | "ewondo" | "douala" | "fulfulde";

export const translations = {
  fr: {
    nav: { associations: "Mes Associations", dashboard: "Tableau de bord", tontines: "Mes Tontines", membres: "Membres", cotisations: "Cotisations", sessions: "Sessions & Tirage", prets: "Prêts & Crédit", solidarite: "Solidarité", epargne: "Épargne & Invest.", marketplace: "Marketplace", evenements: "Événements", chat: "Chat de groupe", conseils: "Conseils IA", rapports: "Rapports", profil: "Mon Profil", gamification: "Gamification", academie: "Académie", aide: "Aide & Support", docs: "Documentation API", parametres: "Paramètres", deconnexion: "Déconnexion", fonctionnalites: "Fonctionnalités", produit: "Produit", ressources: "Ressources", tarifs: "Tarifs", modules: "Modules", modeles_association: "Modèles d'Association", about: "À Propos", security: "Sécurité", mobile: "Mobile", developers: "Développeurs", how_it_works: "Comment ça marche" },
    common: { save: "Enregistrer", cancel: "Annuler", close: "Fermer", add: "Ajouter", edit: "Modifier", delete: "Supprimer", confirm: "Confirmer", search: "Rechercher", filter: "Filtrer", loading: "Chargement...", success: "Succès", error: "Erreur", back: "Retour", next: "Suivant", previous: "Précédent", submit: "Soumettre", create: "Créer", update: "Mettre à jour", view: "Voir", active: "Actif", inactive: "Inactif", pending: "En attente", completed: "Terminé", cancelled: "Annulé", yes: "Oui", no: "Non", total: "Total", amount: "Montant", date: "Date", status: "Statut", actions: "Actions", name: "Nom", description: "Description", members: "Membres", type: "Type", frequency: "Fréquence", balance: "Solde" },
    tontine: { create: "Créer une tontine", name: "Nom de la tontine", description: "Description", type: "Type de tontine", frequency: "Fréquence des séances", maxMembers: "Membres maximum", contributionAmount: "Montant de cotisation", partAmount: "Montant d'une part", allocationMethod: "Méthode d'attribution", allocationFixed: "Montant fixe", allocationPercent: "Pourcentage de la cagnotte", maxPartsPerSession: "Parts max par séance", caisseBalance: "Caisse (reliquat)", caisseLoanRate: "Taux d'intérêt caisse (%/mois)", rules: "Règlement intérieur", region: "Région", isPublic: "Tontine publique" },
    frequency: { weekly: "Hebdomadaire", biweekly: "Bimensuel (toutes les 2 semaines)", monthlyDay: "Jour fixe du mois", monthlyNthWeekday: "Nième jour de la semaine du mois", monthlyFirstAfter: "Premier jour après le N du mois", monthlyLastWeekday: "Dernier jour de la semaine du mois", quarterly: "Trimestriel", customInterval: "Intervalle personnalisé (jours)", days: { 0: "Dimanche", 1: "Lundi", 2: "Mardi", 3: "Mercredi", 4: "Jeudi", 5: "Vendredi", 6: "Samedi" }, nth: { 1: "1er", 2: "2ème", 3: "3ème", 4: "4ème", 5: "Dernier" }, examples: { firstSat: "1er Samedi du mois", firstSun: "1er Dimanche du mois", firstSatAfter5: "1er Samedi après le 5", day15: "Le 15 de chaque mois" } },
    session: { create: "Créer une séance", beneficiaries: "Bénéficiaires", reliquat: "Reliquat en caisse", partsAvailable: "Parts disponibles", addBeneficiary: "Ajouter un bénéficiaire", parts: "Parts", caisseLoan: "Prêt sur caisse", repayNextSession: "Remboursement à la prochaine séance" },
    caisse: { title: "Gestion de la caisse", balance: "Solde en caisse", history: "Historique", addLoan: "Prêter depuis la caisse", loan: "Prêt caisse", borrower: "Emprunteur", rate: "Taux mensuel", duration: "Durée (mois)", dueSession: "Séance de remboursement", totalDue: "Total dû", repaid: "Remboursé" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Langue", addLang: "Ajouter une langue" },
    pricing: { title: "Gratuit & Open Source", subtitle: "Toutes les fonctionnalités, pour toujours, sans carte bancaire", free: "Gratuit", forever: "Pour toujours", allFeatures: "Toutes les fonctionnalités incluses", github: "Code source sur GitHub", selfHost: "Auto-hébergeable", openSource: "Open Source MIT/Apache 2.0" },
    association: { create: "Créer une association", join: "Rejoindre", myAssociations: "Mes Associations", selector: "Sélecteur d'Association", allAssociations: "Toutes mes associations", consolidatedView: "Vue consolidée", wizard: { step1: "Identité", step2: "Modèle", step3: "Activités", step4: "Bureau", step5: "Adhésion", step6: "Règlement", step7: "Lancement" }, templates: { BLANK: "Configuration personnalisée", A30: "Modèle A30 — Amicale du Trente", NDI_MBE: "Modèle NDI MBE — Fonds Investissement", AMSED: "Modèle AMSED — Amicale de Section" }, type: { TONTINE_CLUB: "Club de Tontine 🔄", COOPERATIVE: "Coopérative 🤝", SOLIDARITY: "Fonds de Solidarité ❤️", INVESTMENT: "Fonds d'Investissement 📈", AGRICULTURAL: "Groupement Agricole 🌾", MUTUAL: "Mutuelle 🏥", OTHER: "Autre 🌍" }, status: { ACTIVE: "Active", SUSPENDED: "Suspendue", DISSOLVED: "Dissoute" }, roles: { MEMBER: "Membre", PRESIDENT: "Président(e)", VICE_PRESIDENT: "Vice-Président(e)", SECRETARY: "Secrétaire Général(e)", SECRETARY_ADJ: "Secrétaire Adjoint(e)", TREASURER: "Trésorier(ère)", TREASURER_ADJ: "Trésorier(ère) Adjoint(e)", SOLIDARITY_OFFICER: "Resp. Solidarité", NATURE_OFFICER: "Resp. Nature", AUDITOR: "Commissaire aux Comptes", CENSOR: "Censeur", ADVISOR: "Conseiller(ère)", FOUNDER: "Fondateur(trice)" }, activities: { TONTINE_ROTATIVE: "Tontine Rotative 🔄", TONTINE_ASCA: "ASCA 🏦", TONTINE_ENCHERES: "Enchères 🔨", EPARGNE: "Épargne Collective 💰", AIDE_SOLIDAIRE: "Fonds d'Aide ❤️", PRET: "Prêts Internes 🤝", NATURE: "Tontine Nature 🌾", INVESTISSEMENT: "Investissement 📈", ACHATS_GROUPES: "Achats Groupés 🛒", COLLECTION: "Collection 📋" }, participation: { MANDATORY: "Obligatoire", OPTIONAL: "Facultatif", CONDITIONAL: "Conditionnel" }, distribution: { ROTATION: "Rotation fixe", LOTTERY_MONTHLY: "Tirage mensuel", LOTTERY_UNIQUE: "Tirage unique cycle", AUCTION: "Enchères publiques", MERIT: "Mérite / Ancienneté", NEED: "Urgence / Besoin", HYBRID: "Hybride" }, socialAid: { ILLNESS_MEMBER: "Maladie - Membre", ILLNESS_SPOUSE: "Maladie - Conjoint(e)", DEATH_MEMBER: "Décès - Membre", DEATH_SPOUSE: "Décès - Conjoint(e)", DEATH_CHILD_UNDER5: "Décès Enfant (<5 ans)", DEATH_CHILD_OVER5: "Décès Enfant (>5 ans)", DEATH_PARENT: "Décès Parent", MARRIAGE: "Mariage", BIRTH: "Naissance", BIRTH_TWINS: "Jumeaux", OTHER: "Autre" }, meetings: { REGULAR: "Réunion ordinaire", EXTRAORDINARY: "Extraordinaire", AG_ORDINARY: "AG Ordinaire", AG_EXTRAORDINARY: "AG Extraordinaire" }, attendance: { PRESENT: "Présent", LATE: "En retard", ABSENT: "Absent", EXCUSED: "Excusé" } }
  },
  en: {
    nav: { associations: "My Associations", dashboard: "Dashboard", tontines: "My Tontines", membres: "Members", cotisations: "Contributions", sessions: "Sessions & Draw", prets: "Loans & Credit", solidarite: "Solidarity", epargne: "Savings & Invest.", marketplace: "Marketplace", evenements: "Events", chat: "Group Chat", conseils: "AI Advisor", rapports: "Reports", profil: "My Profile", gamification: "Gamification", academie: "Academy", aide: "Help & Support", docs: "API Docs", parametres: "Settings", deconnexion: "Sign out", fonctionnalites: "Features", produit: "Product", ressources: "Resources", tarifs: "Pricing", modules: "Modules", modeles_association: "Association Templates", about: "About", security: "Security", mobile: "Mobile", developers: "Developers", how_it_works: "How it works" },
    common: { save: "Save", cancel: "Cancel", close: "Close", add: "Add", edit: "Edit", delete: "Delete", confirm: "Confirm", search: "Search", filter: "Filter", loading: "Loading...", success: "Success", error: "Error", back: "Back", next: "Next", previous: "Previous", submit: "Submit", create: "Create", update: "Update", view: "View", active: "Active", inactive: "Inactive", pending: "Pending", completed: "Completed", cancelled: "Cancelled", yes: "Yes", no: "No", total: "Total", amount: "Amount", date: "Date", status: "Status", actions: "Actions", name: "Name", description: "Description", members: "Members", type: "Type", frequency: "Frequency", balance: "Balance" },
    tontine: { create: "Create a tontine", name: "Tontine name", description: "Description", type: "Tontine type", frequency: "Session frequency", maxMembers: "Maximum members", contributionAmount: "Contribution amount", partAmount: "Share amount", allocationMethod: "Allocation method", allocationFixed: "Fixed amount", allocationPercent: "Percentage of pot", maxPartsPerSession: "Max shares per session", caisseBalance: "Treasury (remainder)", caisseLoanRate: "Treasury loan rate (%/month)", rules: "Internal rules", region: "Region", isPublic: "Public tontine" },
    frequency: { weekly: "Weekly", biweekly: "Biweekly (every 2 weeks)", monthlyDay: "Fixed day of month", monthlyNthWeekday: "Nth weekday of month", monthlyFirstAfter: "First weekday after day N of month", monthlyLastWeekday: "Last weekday of month", quarterly: "Quarterly", customInterval: "Custom interval (days)", days: { 0: "Sunday", 1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday", 5: "Friday", 6: "Saturday" }, nth: { 1: "1st", 2: "2nd", 3: "3rd", 4: "4th", 5: "Last" }, examples: { firstSat: "1st Saturday of month", firstSun: "1st Sunday of month", firstSatAfter5: "1st Saturday after 5th", day15: "The 15th of each month" } },
    session: { create: "Create session", beneficiaries: "Beneficiaries", reliquat: "Remainder in treasury", partsAvailable: "Available shares", addBeneficiary: "Add beneficiary", parts: "Shares", caisseLoan: "Treasury loan", repayNextSession: "Repayment at next session" },
    caisse: { title: "Treasury management", balance: "Treasury balance", history: "History", addLoan: "Lend from treasury", loan: "Treasury loan", borrower: "Borrower", rate: "Monthly rate", duration: "Duration (months)", dueSession: "Repayment session", totalDue: "Total due", repaid: "Repaid" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Language", addLang: "Add language" },
    pricing: { title: "Free & Open Source", subtitle: "All features, forever, no credit card required", free: "Free", forever: "Forever", allFeatures: "All features included", github: "Source code on GitHub", selfHost: "Self-hostable", openSource: "Open Source MIT/Apache 2.0" },
    association: { create: "Create association", join: "Join", myAssociations: "My Associations", selector: "Association Selector", allAssociations: "All my associations", consolidatedView: "Consolidated view", wizard: { step1: "Identity", step2: "Template", step3: "Activities", step4: "Bureau", step5: "Membership", step6: "Rules", step7: "Launch" }, templates: { BLANK: "Custom setup", A30: "A30 — Friendly Association", NDI_MBE: "NDI MBE — Investment Fund", AMSED: "AMSED — Section Association" }, type: { TONTINE_CLUB: "Tontine Club 🔄", COOPERATIVE: "Cooperative 🤝", SOLIDARITY: "Solidarity Fund ❤️", INVESTMENT: "Investment Fund 📈", AGRICULTURAL: "Agricultural Group 🌾", MUTUAL: "Mutual Aid 🏥", OTHER: "Other 🌍" }, status: { ACTIVE: "Active", SUSPENDED: "Suspended", DISSOLVED: "Dissolved" }, roles: { MEMBER: "Member", PRESIDENT: "President", VICE_PRESIDENT: "Vice-President", SECRETARY: "Secretary General", SECRETARY_ADJ: "Deputy Secretary", TREASURER: "Treasurer", TREASURER_ADJ: "Deputy Treasurer", SOLIDARITY_OFFICER: "Solidarity Officer", NATURE_OFFICER: "Nature Officer", AUDITOR: "Auditor", CENSOR: "Censor", ADVISOR: "Advisor", FOUNDER: "Founder" }, activities: { TONTINE_ROTATIVE: "Rotating Tontine 🔄", TONTINE_ASCA: "ASCA Fund 🏦", TONTINE_ENCHERES: "Auction Tontine 🔨", EPARGNE: "Collective Savings 💰", AIDE_SOLIDAIRE: "Solidarity Fund ❤️", PRET: "Internal Loans 🤝", NATURE: "Nature Tontine 🌾", INVESTISSEMENT: "Investment 📈", ACHATS_GROUPES: "Group Purchases 🛒", COLLECTION: "Session Fee 📋" }, participation: { MANDATORY: "Mandatory", OPTIONAL: "Optional", CONDITIONAL: "Conditional" }, distribution: { ROTATION: "Fixed rotation", LOTTERY_MONTHLY: "Monthly draw", LOTTERY_UNIQUE: "Unique cycle draw", AUCTION: "Public auction", MERIT: "Merit / Seniority", NEED: "Urgency / Need", HYBRID: "Hybrid" }, socialAid: { ILLNESS_MEMBER: "Illness - Member", ILLNESS_SPOUSE: "Illness - Spouse", DEATH_MEMBER: "Death - Member", DEATH_SPOUSE: "Death - Spouse", DEATH_CHILD_UNDER5: "Death - Child (<5y)", DEATH_CHILD_OVER5: "Death - Child (>5y)", DEATH_PARENT: "Death - Parent", MARRIAGE: "Marriage", BIRTH: "Birth", BIRTH_TWINS: "Twins", OTHER: "Other" }, meetings: { REGULAR: "Regular meeting", EXTRAORDINARY: "Extraordinary", AG_ORDINARY: "Ordinary GA", AG_EXTRAORDINARY: "Extraordinary GA" }, attendance: { PRESENT: "Present", LATE: "Late", ABSENT: "Absent", EXCUSED: "Excused" } }
  },
  es: {
    nav: { associations: "Mis Asociaciones", dashboard: "Panel de control", tontines: "Mis Tontinas", membres: "Miembros", cotisations: "Contribuciones", sessions: "Sesiones y Sorteo", prets: "Préstamos y Crédito", solidarite: "Solidaridad", epargne: "Ahorro e Inversión", marketplace: "Mercado", evenements: "Eventos", chat: "Chat grupal", conseils: "Asesor IA", rapports: "Informes", profil: "Mi Perfil", gamification: "Gamificación", academie: "Academia", aide: "Ayuda y Soporte", docs: "Docs API", parametres: "Configuración", deconnexion: "Cerrar sesión", fonctionnalites: "Características", produit: "Producto", ressources: "Recursos", tarifs: "Precios", modules: "Módulos", modeles_association: "Modelos de Asociación", about: "Sobre Nosotros", security: "Seguridad", mobile: "Móvil", developers: "Desarrolladores", how_it_works: "Cómo funciona" },
    common: { save: "Guardar", cancel: "Cancelar", close: "Cerrar", add: "Agregar", edit: "Editar", delete: "Eliminar", confirm: "Confirmar", search: "Buscar", filter: "Filtrar", loading: "Cargando...", success: "Éxito", error: "Error", back: "Atrás", next: "Siguiente", previous: "Anterior", submit: "Enviar", create: "Crear", update: "Actualizar", view: "Ver", active: "Activo", inactive: "Inactivo", pending: "Pendiente", completed: "Completado", cancelled: "Cancelado", yes: "Sí", no: "No", total: "Total", amount: "Monto", date: "Fecha", status: "Estado", actions: "Acciones", name: "Nombre", description: "Descripción", members: "Miembros", type: "Tipo", frequency: "Frecuencia", balance: "Saldo" },
    tontine: { create: "Crear una tontina", name: "Nombre de la tontina", description: "Descripción", type: "Tipo de tontina", frequency: "Frecuencia de sesiones", maxMembers: "Miembros máximos", contributionAmount: "Monto de contribución", partAmount: "Monto por parte", allocationMethod: "Método de asignación", allocationFixed: "Monto fijo", allocationPercent: "Porcentaje del bote", maxPartsPerSession: "Partes máx por sesión", caisseBalance: "Caja (remanente)", caisseLoanRate: "Tasa préstamo caja (%/mes)", rules: "Reglamento interno", region: "Región", isPublic: "Tontina pública" },
    frequency: { weekly: "Semanal", biweekly: "Quincenal (cada 2 semanas)", monthlyDay: "Día fijo del mes", monthlyNthWeekday: "Nésimo día de la semana del mes", monthlyFirstAfter: "Primer día después del día N del mes", monthlyLastWeekday: "Último día de la semana del mes", quarterly: "Trimestral", customInterval: "Intervalo personalizado (días)", days: { 0: "Domingo", 1: "Lunes", 2: "Martes", 3: "Miércoles", 4: "Jueves", 5: "Viernes", 6: "Sábado" }, nth: { 1: "1°", 2: "2°", 3: "3°", 4: "4°", 5: "Último" }, examples: { firstSat: "1er Sábado del mes", firstSun: "1er Domingo del mes", firstSatAfter5: "1er Sábado después del 5", day15: "El 15 de cada mes" } },
    session: { create: "Crear sesión", beneficiaries: "Beneficiarios", reliquat: "Remanente en caja", partsAvailable: "Partes disponibles", addBeneficiary: "Agregar beneficiario", parts: "Partes", caisseLoan: "Préstamo de caja", repayNextSession: "Reembolso en la próxima sesión" },
    caisse: { title: "Gestión de la caja", balance: "Saldo en caja", history: "Historial", addLoan: "Prestar desde la caja", loan: "Préstamo de caja", borrower: "Prestatario", rate: "Tasa mensual", duration: "Duración (meses)", dueSession: "Sesión de reembolso", totalDue: "Total adeudado", repaid: "Reembolsado" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Idioma", addLang: "Agregar idioma" },
    pricing: { title: "Gratis y Código Abierto", subtitle: "Todas las funcionalidades, para siempre, sin tarjeta de crédito", free: "Gratis", forever: "Para siempre", allFeatures: "Todas las funciones incluidas", github: "Código fuente en GitHub", selfHost: "Auto-alojable", openSource: "Código abierto MIT/Apache 2.0" },
    association: { create: "Crear asociación", join: "Unirse", myAssociations: "Mis Asociaciones", selector: "Selector de Asociación", allAssociations: "Todas mis asociaciones", consolidatedView: "Vista consolidada", wizard: { step1: "Identidad", step2: "Plantilla", step3: "Actividades", step4: "Órgano directivo", step5: "Membresía", step6: "Reglamento", step7: "Lanzamiento" }, templates: { BLANK: "Config. personalizada", A30: "Plantilla A30", NDI_MBE: "NDI MBE — Fondo Inversión", AMSED: "AMSED — Asociación de Sección" }, type: { TONTINE_CLUB: "Club de Tontina 🔄", COOPERATIVE: "Cooperativa 🤝", SOLIDARITY: "Fondo Solidaridad ❤️", INVESTMENT: "Fondo Inversión 📈", AGRICULTURAL: "Grupo Agrícola 🌾", MUTUAL: "Mutua 🏥", OTHER: "Otro 🌍" }, status: { ACTIVE: "Activo", SUSPENDED: "Suspendido", DISSOLVED: "Disuelto" }, roles: { MEMBER: "Miembro", PRESIDENT: "Presidente/a", VICE_PRESIDENT: "Vicepresidente/a", SECRETARY: "Secretario/a General", SECRETARY_ADJ: "Secretario/a Adjunto/a", TREASURER: "Tesorero/a", TREASURER_ADJ: "Tesorero/a Adjunto/a", SOLIDARITY_OFFICER: "Resp. Solidaridad", NATURE_OFFICER: "Resp. Naturaleza", AUDITOR: "Auditor/a", CENSOR: "Censor/a", ADVISOR: "Asesor/a", FOUNDER: "Fundador/a" }, activities: { TONTINE_ROTATIVE: "Tontina Rotativa 🔄", TONTINE_ASCA: "ASCA 🏦", TONTINE_ENCHERES: "Subasta 🔨", EPARGNE: "Ahorro Colectivo 💰", AIDE_SOLIDAIRE: "Fondo Ayuda ❤️", PRET: "Préstamos 🤝", NATURE: "Tontina Natural 🌾", INVESTISSEMENT: "Inversión 📈", ACHATS_GROUPES: "Compras Grupales 🛒", COLLECTION: "Cuota Sesión 📋" }, participation: { MANDATORY: "Obligatorio", OPTIONAL: "Opcional", CONDITIONAL: "Condicional" }, distribution: { ROTATION: "Rotación fija", LOTTERY_MONTHLY: "Sorteo mensual", LOTTERY_UNIQUE: "Sorteo único", AUCTION: "Subasta pública", MERIT: "Mérito", NEED: "Necesidad", HYBRID: "Híbrido" }, socialAid: { ILLNESS_MEMBER: "Enfermedad Miembro", ILLNESS_SPOUSE: "Enfermedad Cónyuge", DEATH_MEMBER: "Fallecimiento Miembro", DEATH_SPOUSE: "Fallecimiento Cónyuge", DEATH_CHILD_UNDER5: "Fallecimiento Hijo (<5a)", DEATH_CHILD_OVER5: "Fallecimiento Hijo (>5a)", DEATH_PARENT: "Fallecimiento Padre/Madre", MARRIAGE: "Matrimonio", BIRTH: "Nacimiento", BIRTH_TWINS: "Gemelos", OTHER: "Otro" }, meetings: { REGULAR: "Reunión ordinaria", EXTRAORDINARY: "Extraordinaria", AG_ORDINARY: "AG Ordinaria", AG_EXTRAORDINARY: "AG Extraordinaria" }, attendance: { PRESENT: "Presente", LATE: "Tarde", ABSENT: "Ausente", EXCUSED: "Excusado" } }
  },
  de: {
    nav: { associations: "Meine Vereine", dashboard: "Dashboard", tontines: "Meine Tontinen", membres: "Mitglieder", cotisations: "Beiträge", sessions: "Sitzungen & Auslosung", prets: "Darlehen & Kredit", solidarite: "Solidarität", epargne: "Sparen & Investieren", marketplace: "Marktplatz", evenements: "Veranstaltungen", chat: "Gruppenchat", conseils: "KI-Berater", rapports: "Berichte", profil: "Mein Profil", gamification: "Gamification", academie: "Akademie", aide: "Hilfe & Support", docs: "API-Dokumentation", parametres: "Einstellungen", deconnexion: "Abmelden", fonctionnalites: "Funktionen", produit: "Produkt", ressources: "Ressourcen", tarifs: "Preise", modules: "Module", modeles_association: "Vereinsvorlagen", about: "Über Uns", security: "Sicherheit", mobile: "Mobil", developers: "Entwickler", how_it_works: "Wie es funktioniert" },
    common: { save: "Speichern", cancel: "Abbrechen", close: "Schließen", add: "Hinzufügen", edit: "Bearbeiten", delete: "Löschen", confirm: "Bestätigen", search: "Suchen", filter: "Filtern", loading: "Laden...", success: "Erfolg", error: "Fehler", back: "Zurück", next: "Weiter", previous: "Zurück", submit: "Absenden", create: "Erstellen", update: "Aktualisieren", view: "Anzeigen", active: "Aktiv", inactive: "Inaktiv", pending: "Ausstehend", completed: "Abgeschlossen", cancelled: "Abgebrochen", yes: "Ja", no: "Nein", total: "Gesamt", amount: "Betrag", date: "Datum", status: "Status", actions: "Aktionen", name: "Name", description: "Beschreibung", members: "Mitglieder", type: "Typ", frequency: "Häufigkeit", balance: "Guthaben" },
    tontine: { create: "Tontine erstellen", name: "Tontinenname", description: "Beschreibung", type: "Tontinentyp", frequency: "Sitzungshäufigkeit", maxMembers: "Maximale Mitglieder", contributionAmount: "Beitragshöhe", partAmount: "Anteilsbetrag", allocationMethod: "Zuteilungsmethode", allocationFixed: "Fester Betrag", allocationPercent: "Prozentsatz des Topfes", maxPartsPerSession: "Max. Anteile pro Sitzung", caisseBalance: "Kasse (Rest)", caisseLoanRate: "Kassendarlehensrate (%/Monat)", rules: "Interne Regeln", region: "Region", isPublic: "Öffentliche Tontine" },
    frequency: { weekly: "Wöchentlich", biweekly: "Zweiwöchentlich", monthlyDay: "Fester Tag des Monats", monthlyNthWeekday: "N-ter Wochentag des Monats", monthlyFirstAfter: "Erster Wochentag nach dem N. des Monats", monthlyLastWeekday: "Letzter Wochentag des Monats", quarterly: "Vierteljährlich", customInterval: "Benutzerdefiniertes Intervall (Tage)", days: { 0: "Sonntag", 1: "Montag", 2: "Dienstag", 3: "Mittwoch", 4: "Donnerstag", 5: "Freitag", 6: "Samstag" }, nth: { 1: "1.", 2: "2.", 3: "3.", 4: "4.", 5: "Letzter" }, examples: { firstSat: "1. Samstag des Monats", firstSun: "1. Sonntag des Monats", firstSatAfter5: "1. Samstag nach dem 5.", day15: "Der 15. jeden Monats" } },
    session: { create: "Sitzung erstellen", beneficiaries: "Begünstigte", reliquat: "Rest in der Kasse", partsAvailable: "Verfügbare Anteile", addBeneficiary: "Begünstigten hinzufügen", parts: "Anteile", caisseLoan: "Kassendarlehen", repayNextSession: "Rückzahlung bei der nächsten Sitzung" },
    caisse: { title: "Kassenverwaltung", balance: "Kassenbestand", history: "Verlauf", addLoan: "Aus der Kasse leihen", loan: "Kassendarlehen", borrower: "Kreditnehmer", rate: "Monatlicher Zinssatz", duration: "Laufzeit (Monate)", dueSession: "Rückzahlungssitzung", totalDue: "Fälliger Gesamtbetrag", repaid: "Zurückgezahlt" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Sprache", addLang: "Sprache hinzufügen" },
    pricing: { title: "Kostenlos & Open Source", subtitle: "Alle Funktionen, für immer, ohne Kreditkarte", free: "Kostenlos", forever: "Für immer", allFeatures: "Alle Funktionen inklusive", github: "Quellcode auf GitHub", selfHost: "Selbst-hostbar", openSource: "Open Source MIT/Apache 2.0" },
    association: { create: "Verein erstellen", join: "Beitreten", myAssociations: "Meine Vereine", selector: "Vereinsauswahl", allAssociations: "Alle meine Vereine", consolidatedView: "Konsolidierte Ansicht", wizard: { step1: "Identität", step2: "Vorlage", step3: "Aktivitäten", step4: "Vorstand", step5: "Mitgliedschaft", step6: "Satzung", step7: "Start" }, templates: { BLANK: "Eigene Konfiguration", A30: "Vorlage A30", NDI_MBE: "NDI MBE — Investmentfonds", AMSED: "AMSED — Sektionsverein" }, type: { TONTINE_CLUB: "Tontinen-Klub 🔄", COOPERATIVE: "Kooperative 🤝", SOLIDARITY: "Solidaritätsfonds ❤️", INVESTMENT: "Investmentfonds 📈", AGRICULTURAL: "Landwirtschaftsgruppe 🌾", MUTUAL: "Gegenseitigkeitshilfe 🏥", OTHER: "Sonstige 🌍" }, status: { ACTIVE: "Aktiv", SUSPENDED: "Ausgesetzt", DISSOLVED: "Aufgelöst" }, roles: { MEMBER: "Mitglied", PRESIDENT: "Präsident(in)", VICE_PRESIDENT: "Vizepräsident(in)", SECRETARY: "Generalsekretär(in)", SECRETARY_ADJ: "Stellv. Sekretär(in)", TREASURER: "Kassenwart/-wärtin", TREASURER_ADJ: "Stellv. Kassenwart", SOLIDARITY_OFFICER: "Solidaritätsbeauftragte(r)", NATURE_OFFICER: "Naturbeauftragte(r)", AUDITOR: "Kassenprüfer(in)", CENSOR: "Zensor(in)", ADVISOR: "Berater(in)", FOUNDER: "Gründer(in)" }, activities: { TONTINE_ROTATIVE: "Rotierende Tontine 🔄", TONTINE_ASCA: "ASCA-Fonds 🏦", TONTINE_ENCHERES: "Auktions-Tontine 🔨", EPARGNE: "Gemeinschaftssparen 💰", AIDE_SOLIDAIRE: "Solidaritätsfonds ❤️", PRET: "Interne Darlehen 🤝", NATURE: "Natur-Tontine 🌾", INVESTISSEMENT: "Investition 📈", ACHATS_GROUPES: "Gruppenbestellungen 🛒", COLLECTION: "Sitzungsbeitrag 📋" }, participation: { MANDATORY: "Pflicht", OPTIONAL: "Freiwillig", CONDITIONAL: "Bedingt" }, distribution: { ROTATION: "Feste Rotation", LOTTERY_MONTHLY: "Monatliche Auslosung", LOTTERY_UNIQUE: "Einmalige Auslosung", AUCTION: "Öffentliche Auktion", MERIT: "Verdienst", NEED: "Bedarf", HYBRID: "Hybrid" }, socialAid: { ILLNESS_MEMBER: "Krankheit Mitglied", ILLNESS_SPOUSE: "Krankheit Ehegatte", DEATH_MEMBER: "Tod Mitglied", DEATH_SPOUSE: "Tod Ehegatte", DEATH_CHILD_UNDER5: "Tod Kind (<5J)", DEATH_CHILD_OVER5: "Tod Kind (>5J)", DEATH_PARENT: "Tod Elternteil", MARRIAGE: "Heirat", BIRTH: "Geburt", BIRTH_TWINS: "Zwillinge", OTHER: "Sonstige" }, meetings: { REGULAR: "Ordentliche Sitzung", EXTRAORDINARY: "Außerordentlich", AG_ORDINARY: "Ordentliche HV", AG_EXTRAORDINARY: "Außerordentliche HV" }, attendance: { PRESENT: "Anwesend", LATE: "Verspätet", ABSENT: "Abwesend", EXCUSED: "Entschuldigt" } }
  }
} as const;

// TranslationKey is the union of all language translation shapes
export type TranslationKey = (typeof translations)[keyof typeof translations];

// Partial translations for local Cameroonian languages (FR is used as fallback for missing keys)
type NavT = (typeof translations)["fr"]["nav"];
type CommonT = (typeof translations)["fr"]["common"];
type LangT = (typeof translations)["fr"]["lang"];
type LocalPartial = { nav: Partial<NavT>; common: Partial<CommonT>; lang: Partial<LangT> };

export const localTranslations: Record<string, LocalPartial> = {
  ghomala: {
    nav: { associations: "Ndɑ̂p wɔ̂", dashboard: "Sɑ̂ pɑ̂", tontines: "Tontine", membres: "Bwɑ̂m", cotisations: "Lɔk ŋɔ̂n", sessions: "Pɑ̂ sɛ̂s", prets: "Wɔ̂m ŋɔ̂n", solidarite: "Tɛ̂ŋ", epargne: "Lɔk", marketplace: "Ndɑ̂p", evenements: "Pɑ̂", chat: "Pɑ̂ ŋɔ̂m", conseils: "Kɑ̂", rapports: "Wɔ̂", profil: "Kɑ̂ wɔ̂", gamification: "Pɑ̂ lɔk", academie: "Kɑ̂ mɔ̂", aide: "Tɛ̂ŋ", docs: "Kɑ̂", parametres: "Tɑ̂m", deconnexion: "Bɑ̂k" },
    common: { save: "Lɔk", cancel: "Bɑ̂k", close: "Bɑ̂k", add: "Nɑ̂m", edit: "Fɑ̂k", delete: "Bü", confirm: "Tɑ̂m", search: "Tʉ̂n", filter: "Zʉk", loading: "Ɔ̀k...", success: "Wɑ̂", error: "Lô bi tɑ̂", back: "Kɔ̂", next: "Pɛ̂", previous: "Kɔ̂", submit: "Pɛ̂", create: "Nɑ̂m", update: "Fɑ̂k", view: "Kɑ̂", active: "Wɔ̂", inactive: "Bɑ̂k", pending: "Zɔm", completed: "Wɑ̂", cancelled: "Bɑ̂k", yes: "Nɛ̂", no: "Kʉ̂", total: "Pɑ̂ ŋɔ̂n", amount: "Lɑ̂p ŋɔ̂n", date: "Ŋɑ̂n", status: "Tʉ̂m", actions: "Pɑ̂", name: "Tsɔ̂", description: "Kɑ̂", members: "Bwɑ̂m", type: "Tʉ̂m", frequency: "Pɑ̂", balance: "Ŋɔ̂n" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Tʉ̂m pɑ̂", addLang: "Nɑ̂m tʉ̂m" },
  },
  ewondo: {
    nav: { associations: "Minsëm mi woe", dashboard: "Awu biton", tontines: "Tontine", membres: "Bimvom", cotisations: "Ka ñkuñ", sessions: "Mfan", prets: "Bôl ñkuñ", solidarite: "Mfan", epargne: "Bôl", marketplace: "Nda", evenements: "Mañ", chat: "Kal", conseils: "Bot bi toñ", rapports: "Bé", profil: "Bé woe", gamification: "Biton", academie: "Bé mañ", aide: "Mfan", docs: "Bé", parametres: "Tô", deconnexion: "Bôk" },
    common: { save: "Bôl", cancel: "Bôk", close: "Bôk", add: "Ka", edit: "Tô", delete: "Bu", confirm: "Si", search: "Mên", filter: "Yom", loading: "Mân...", success: "Ayé", error: "Mañ ma toñ", back: "Tô awu", next: "Tô fôt", previous: "Tô awu", submit: "Ka fôt", create: "Ka", update: "Tô", view: "Bé", active: "Mân", inactive: "Bôk", pending: "Yom", completed: "Ayé", cancelled: "Bôk", yes: "Iì", no: "Aôo", total: "Biyé mbë", amount: "Mbë ñkuñ", date: "Mvog", status: "Bi", actions: "Mañ", name: "Din", description: "Bé", members: "Bimvom", type: "Bi", frequency: "Fôt", balance: "Ñkuñ" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Bi kal", addLang: "Ka bi kal" },
  },
  douala: {
    nav: { associations: "Mintula mam", dashboard: "Nda bonyé", tontines: "Tontine", membres: "Bato", cotisations: "Yaka ñkuñ", sessions: "Ndé ba", prets: "Bôla ñkuñ", solidarite: "Ntuma", epargne: "Londa", marketplace: "Nda", evenements: "Mañ", chat: "Kal", conseils: "Bato ba kuma", rapports: "Bé", profil: "Bé wam", gamification: "Biton", academie: "Bé mañ", aide: "Ntuma", docs: "Bé", parametres: "Sanga", deconnexion: "Buka" },
    common: { save: "Londa", cancel: "Buka", close: "Buka", add: "Yaka", edit: "Sanga", delete: "Dika", confirm: "Sama", search: "Buka", filter: "Yoma", loading: "Muna...", success: "Yé", error: "Muna ma tuka", back: "Buka mbedi", next: "Tuka", previous: "Buka mbedi", submit: "Yaka fôt", create: "Yaka", update: "Sanga", view: "Bé", active: "Muna", inactive: "Buka", pending: "Yoma", completed: "Yé", cancelled: "Buka", yes: "Ii", no: "Não", total: "Bonyé ñkuñ", amount: "Mbamba ñkuñ", date: "Ndé", status: "Kuma", actions: "Mañ", name: "Din", description: "Bé", members: "Bato", type: "Kuma", frequency: "Ndé", balance: "Ñkuñ" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Kuma lokola", addLang: "Yaka kuma" },
  },
  fulfulde: {
    nav: { associations: "Leñolji am", dashboard: "Saare fof", tontines: "Tontine", membres: "Ɓiɓɓe", cotisations: "Naatirde kaalis", sessions: "Jultirde", prets: "Ɗaɓɓo kaalis", solidarite: "Jultirde", epargne: "Hobbu", marketplace: "Saare", evenements: "Gollorɗe", chat: "Haala", conseils: "Tawtorɗo", rapports: "Bé", profil: "Maa wonde", gamification: "Gollorɗe", academie: "Jangirde", aide: "Jultirde", docs: "Bé", parametres: "Naatirde", deconnexion: "Haɓɓu" },
    common: { save: "Hobbu", cancel: "Haɓɓu", close: "Haɓɓu", add: "Faɗtu", edit: "Waɗtu", delete: "Selu", confirm: "Jaŋtu", search: "Yiɓu", filter: "Suɓu", loading: "Waɗde...", success: "Heɓii", error: "Juumre waɗii", back: "Rewa", next: "Yeɓu", previous: "Rewa", submit: "Naatirde", create: "Faɗtu", update: "Waɗtu", view: "Hito", active: "Waɗde", inactive: "Haɓɓii", pending: "Yiɗndi", completed: "Heɓii", cancelled: "Haɓɓii", yes: "Eey", no: "Alaa", total: "Jimɓe kaalis", amount: "Jinaa kaalis", date: "Ñalnde", status: "Haaɗorde", actions: "Gollal", name: "Innde", description: "Jaaɓi", members: "Ɓiɓɓe", type: "Sifaa", frequency: "Sahaa", balance: "Kaalis" },
    lang: { fr: "Français", en: "English", es: "Español", de: "Deutsch", select: "Demngal", addLang: "Faɗtu demngal" },
  },
};
